### PR TITLE
feat: rename tilt to pinch

### PR DESCRIPTION
**Pull request by gabbopalma**
- [X] rename all tilt references to pinch
- [X] update CHANGELOG.md
- [X] update comments for tilt / pinch

Closes a task of #22

### CODE REVIEW

**Comment by josxha** [comment]
Thanks for the pull request @gabbopalma! We can either add it to the breaking v0.1.2 release or by adding deprecations to the public API add it directly to the v0.0.2 feature release. As you wish. 👍
The CI currently fails because one file is not formated. You can fix it by running `dart format .`

**Comment by gabbopalma** [comment]
I think introducing deprecations in the public API means adding double references to the tilt and pinch properties. This would also mean managing which one to select in their use cases. 
Maybe I'm missing some information about deprecations, but these are the ways I've found to manage the properties that are being deprecated (and not the methods, which are easier). Let me know if you have any ideas.
Currently we can stay in v0.1.2 :)

**Comment by josxha** [comment]
After some time thinking about it, I'd love to release it already with the next 0.0.2 release (sorry about the type in my last message, the breaking release will be 0.1.0 😄). Otherwise the newly added max/min tilt parameters would be renamed immediately. And keeping this pull request up-to-date with the main branch could be trickly.
I agree that these deprecations are not that beautiful (and the package probably doesnt' have real users at the moment anyways) but I think it's a nice way to decrease the amount of breaking releases. 
But don't worry about the deprecations, I'll add them in. Thanks for your pull request,  your changes look good to me. 👍

**Comment by josxha** [comment]
Alright, should be ready to merge now. Sorry for asking for what you prefer and then not going with it. The pull request came just in the right time.😅

**Comment by gabbopalma** [comment]
Don't worry, your choice is definitely good for the purposes of the project. I will see the improvements of the deprecations, I am curious to see what changed ahah.
Well, if that's all, we can close 👍🏼

**Pull request merged**
